version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true #para intereção
    volumes: #para não perder informações quando o container cair
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network  

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app  
      - /usr/src/app/node_modules  
    tty: true
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app  
networks:
  node-network:  
    driver: bridge

  